openstack-charmers/zosci-config

playbooks/juju/pre.yaml

Without this fix, no func-test-pr gets picked up.

Fix func-test-pr determination

---

main.yaml

This will unblock https://review.opendev.org/c/openstack/charm-tempest/+/795759

Add tempest to the list of charms

---

main.yaml

This PR includes the recently added charm cinder-LVM.

Add the cinder-lvm charm to the main YAML file

---

roles/charm-build/tasks/main.yaml
roles/upload-charm/tasks/main.yaml

This reverts commit 9727ca97ef8cc2a88f7eb145bc1b5a4576abcba2.

Revert "Only upload built .charm file for charmcraft charms"

---

zuul.d/jobs.yaml

Add the focal-yoga target for opening the yoga cloud archive for focal.

Add focal-yoga

---

zuul.d/jobs.yaml

This will fix https://review.opendev.org/c/openstack/charm-magpie/+/816027

Add jammy job

---

zuul.d/project-templates.yaml

Add:
* charm-train-functional-jobs
* charm-rocky-functional-jobs

Add train and rocky functional jobs

---

zuul.d/project-templates.yaml

This is to make zosci happy with the new upstream xena Zuul
CI job.

Add upstream openstack-python3-xena-jobs as a placeholder

---

roles/handle-func-test-pr/files/process-func-test-pr.py
roles/handle-func-test-pr/tasks/main.yaml

Move the logic for processing the commit message into a seperate
python script as the ansible module was becomig hard to read and
manage. Update script so that it supports multiple func-test-pr
directives

Support multiple func-test-pr directives

---

zuul.d/project-templates.yaml

Add openstack-tox-py310 from upstream zuul to project templates.

Add openstack-tox-py310 to project templates

---

main.yaml

Add the cinder three par driver

Add cinder three par driver

---

zuul.d/secrets.yaml

This reverts commit 49bdc099ed35881aad6312b9abe2ec6b36eeb3ab.

Revert "Switch to upload artifacts to ps5"

---

playbooks/juju/post.yaml

Related-Bug: http://pad.lv/1979649

Capture /var/snap/simplestreams/common .

---

roles/publish-charm/tasks/main.yaml

Minor fix in concatenation of strings in
publish_charm task

Fix string concat error in publish_charm task

---

roles/publish-charm/tasks/main.yaml
zuul.d/secrets.yaml

Regenerate charmhub_token for uosci-testing-bot
and update corresponding secret.
Fix to escape {{ }} in shell script.

Update secret charmhub_token

---

roles/publish-charm/tasks/main.yaml

Upload charm and upload oci-image tasks
are reversed.

reverse publish charm upload tasks

---

roles/publish-charm/tasks/main.yaml

PR #231 is for debugging purpose and so
the patch is reverted.

revert pr-231

---

main.yaml

Add keystone-openidc to the list of projects to run check jobs.

Add keystone-openidc

---

main.yaml

Add cloudkitty to the list of projects to run check jobs.

added cloudkitty repo

---

main.yaml

Add ironic-dashboard charm[0] to zuul's config.
[0] https://launchpad.net/charm-ironic-dashboard

Add charm-ironic-dashboard

---

main.yaml

Add openstack/openstack-hypervisor to gerrit untrusted projects.

Add charm-openstack-hypervisor to untrusted projects

---

zuul.d/jobs.yaml
zuul.d/project-templates.yaml

Add bobcat jobs and charm-functional-jobs for bobcat.
Also stop running zed jobs on master branches.

Add bobcat jobs and charm-functional-jobs

---

main.yaml

Add aodh-k8s, ceilometer-k8s, gnocchi-k8s to
untrusted projects

Add telemetry k8s charms to untrusted projects

---

playbooks/juju/pre.yaml

zaza-openstack-tests needs this for calls to qemu-img.

Add qemu-utils dependency

---

main.yaml

Add charm-octavia-k8s to untrusted projects

Add octavia k8s charm to untrusted projects

---

main.yaml

Draft until https://review.opendev.org/c/openstack/project-config/+/892650 is merged

Add designate-k8s to untrusted projects

---

main.yaml

Add charm-openstack-exporter-k8s to untrusted projects

---

playbooks/base/post.yaml
roles/upload-swift/tasks/main.yaml
zuul.d/secrets.yaml

Previous attempt failed with "Expecting to Find Domain in User" which seems to be related to missing user and project domain information. This is has been added.

Switch to PS5 for uploads
