playbooks/juju/pre.yaml

When using the > character, a yaml multi line string is
joined with spaces and quoted. When a multi-line is
separated with a | character, the lines are joined with a
new line

Use a pipe instead of > to define command

---

zuul.d/jobs.yaml

These appear to be conflicting with HTTP(S)_PROXY and microstack
lxd builds.

Drop http(s)_proxy env vars

---

playbooks/charm/build.yaml
roles/charm-build/tasks/main.yaml
zuul.d/jobs.yaml

This change introduces a new playbook that can be integrated into the
build pipeline to build and archive a reactive charm to allow for later
jobs to retrieve it. The existing build step should then work to either download
the built artifact or build it if missing.
This fallback code path allows reusing the existing charm-build role in the new
playbook because we can import the existing role (`charm-build`) in the
charm build playbook and it will correctly build the charm. At that point, the
playbook will archive the built artifact under a build-specific identifier
generated by zuul in Serverstack's Swift.

Add support for building a reactive charm and archiving that

---

playbooks/juju/run.yaml
roles/setup-test-fixtures/tasks/main.yaml
zuul.d/jobs.yaml

This change introduces a new Role that can be
use to encapsulate all of our "get this test
file from storage and put it somewhere" type
of setup tasks.

Add support for fetching the trilio vault license from Swift

---

playbooks/juju/pre.yaml
roles/charm-build/tasks/main.yaml

This change also adds libmysqlclient-dev and libpq-dev to the charm-build role

Add libmysqlclient-dev

---

playbooks/juju/run.yaml

Charm build sometimes has additional dependencies so
we need to be able to install those before running

Revoke sudo after charm build

---

playbooks/juju/pre.yaml

Because this isn't using bash, it is probably just
a cosmetic change; however, we should have commands
that are safe to run in any shell rather than hoping
for a correct interpretation.

Fix line breaks in juju bootstrap command

---

main.yaml

ceph-iscsi, magnum, magnum-dashboard, manila-dashboard,
manila-netapp.
Related: https://review.opendev.org/q/topic:zosci

Add new charms

---

zuul.d/pipelines.yaml

Some features within projects like microstack are currently experimental
and the gate continues to have problems due to experimental feature
support (i.e. lvm volumes). Add an experimental pipeline which allows
the experimental tests to be run, but are non-voting tests.

Add experimental pipeline

---

zuul.d/pipelines.yaml

Commit 0af73f36 has an error in the formatting. The Verified
voting line was uncommented, but the dictionary {} left for
the gerrit config.

Fix yaml formatting error

---

playbooks/juju/post.yaml

Juju crashdump is conservative when it comes to retrieving data
from /etc. Add apache2 and haproxy subdirectories to help debug
a class of issues.
Related-Bug: #1930654

post: Retrieve Apache and HAProxy config in crashdump

---

zuul.d/jobs.yaml

The default timeout of two hours is unfortunately not enough and
lead to false negative test results.
Example timeout: https://openstack-ci-reports.ubuntu.com/artifacts/f94/778991/12/check/focal-victoria-ha-ovn/f94976f/index.html

jobs/func-target: Increase default job timeout

---

zuul.d/jobs.yaml

MicroStack jobs seem to have started taking more than 2 hours. Let's
adjust it to avoid premature failures while we figure possible test
infra changes that might have caused it.

Adjust job timeout to avoid premature failures

---

playbooks/juju/post.yaml

Some class of issues would be easier to analyze with access to
OVS/OVN configuration and DBs.

post/crashdump: Retrieve OVS/OVN conf and DBs

---

roles/charm-build/tasks/main.yaml

Set the zuul_work_dir by charm build type rather than assuming its
a reactive charm. Example failure *1
*1 https://openstack-ci-reports.ubuntu.com/artifacts/f83/803940/6/check/focal/f83c48d/job-output.json

Set the zuul_work_dir by build type

---

roles/upload-charm/tasks/main.yaml

Commit f728f884e changed the archive built charm step. After that
commit two tasks both register the charm_archived variable. Which
task is run depends on the `when` clause. The problem with this is
that the second task always overwrites the contents of `charm_archived`
even if the tasks `when` condition is not met. If the second task is
skipped then `charm_archived` is a boolean set to False. If the task
runs `charm_archived` is a dict containing the return code of the tar
command. If the second task is skipped then a subsequent task fails
because it assume `charm_archived` to be a dict *1
This patch changes the archive tasks to register different variables
and then updates the upload task to check both variables.
There is also a drive-by fix to the charmcraft tar step to stop
it …

Fix upload step

---

roles/upload-swift/tasks/main.yaml

This coincides with an update to our swift buckets to allow all of the
listings to work correctly (/ -> index.html).

Remove index.html from generated artifact links

---

README.md
zuul.d/project-templates.yaml

charm-functional-jobs is the 'default' set of jobs for gate-testing
charms.  Remove groovy-victoria as it is now EOL.

Remove groovy-victoria from charm-functional-jobs

---

roles/upload-charm/tasks/main.yaml

The charmcraft build outputs to the current directory so the tar
is of the current directory too unlike reactive charms which are
built in a subdirectory and the tar ball created from a few directories
up.
Although the charm being built should be excluded from the archive
sometimes `tar: .: file changed as we read it ` errors are seen.
To guard against this build the tar ball in a seperate directory.

Tar charmcraft build charms in temp dir

---

playbooks/new-tenant-juju/pre.yaml

In addition to truncating the final result, it shortens
the initial name by using the change rather than the
job name.

This change truncates the tenant name

---

roles/charm-build/tasks/main.yaml
roles/upload-charm/tasks/main.yaml

611f6c1 and 32c0131 were reverted due to a non-fatal error in
handling upload debug logs:
`
2021-10-05 09:23:23.942868 | TASK [upload-charm : Print upload failures]
2021-10-05 09:23:24.075925 | xenial-medium | ok:
2021-10-05 09:23:24.076302 | xenial-medium | {
2021-10-05 09:23:24.076406 | xenial-medium |   "upload_results_reactive.upload_failures": "VARIABLE IS NOT DEFINED!: 'dict object' has no attribute 'upload_failures'"
2021-10-05 09:23:24.076500 | xenial-medium | }
`
https://openstack-ci-reports.ubuntu.com/artifacts/6dd/811998/2/check/charm-build/6dd1ac0/job-output.txt
This PR contains the changes from 611f6c1 and 32c0131. In addition
the 'Return (charmcraft|reactive) charm to Zuul' job definitions
now have a charm type conditional.

Only upload built .charm file for charmcraft charms

---

roles/charm-build/tasks/main.yaml

Charmcraft charms are being rebuilt when running functional tests
even if the built charm was sucessfully downloaded. This is because
the download step is not echoing the phrase:
"successfully fetched built" which the build step checks for.

Fix charmcraft charm being rebuilt

---

roles/charm-build/tasks/main.yaml

Once the built charm is downloaded it still has zuul buildset
as part for the filename. So, rename it to the original name
so that it is picked up correctly by the zaza bundles.

Rename charmcraft built charm after downloading

---

roles/upload-charm/tasks/main.yaml

If the build job was skipped becuase the built charm was downloaded
then the archive jobs fail as there is not build rc. This PR fixes that
in the same way as is done with other jobs by checking the rc attribute
is present first.

Fix archive job if build job was skipped

---

roles/charm-build/tasks/main.yaml

Before building a charm zosci attempts to download it from swift.
If it succeeds then the build is skipped. However the download
always succeeds, if the artifact isn't present in swift the
'downloaded' charm just contains 'NoSuchKey'
```
$ curl -o /tmp/foo.charm  http://10.245.161.162:80/swift/v1/zuul-built-charms/foo.charm
$ cat /tmp/foo.charm
NoSuchKey
```
For reactive charms the charm is downloaded and then untar'd but
the untar fails which stop job from echoing the success message.
For charmcraft charms there is no untar step so the job appearts
to have correctly downloaded the charm.
This PR adds a very rudimentary check on the downloaded file
to ascertain whether the charm was downloaded correctly.

Run rudimentary checks on downloaded file

---

zuul.d/project-templates.yaml

This adds a new job that doesn't include py35, and aligns
with https://review.opendev.org/c/openstack/openstack-zuul-jobs/+/814126/4/zuul.d/project-templates.yaml

Add charm-yoga-unit-jobs

---

zuul.d/jobs.yaml

Add the jammy-yoga target for running tests with OpenStack Yoga on
Ubuntu 22.04 Jammy Jellyfish.

Add jammy-yoga

---

zuul.d/project-templates.yaml

These will be used for the the charm cycle that introduces Yoga.
Any non-voting jobs will need to be changed to voting at a later
date once fully supported.

Add charm-yoga-functional-jobs

---

zuul.d/jobs.yaml

While running py39 on impish is preferred, we can't do that until
the [1] is available in our installed version of zuul. For now,
run py39 on focal.
https://opendev.org/zuul/zuul/commit/873028e309b0d0bae65c667e997939302d1be5a5

Run tox-py39 on focal-medium

---

zuul.d/jobs.yaml

The current configuration makes use of a behavior of OpenStack
Neutron with ML2/OVS which was to provide a dnsmasq-based DNS
forwarder on the .2 address of project networks.
This behavior is not retained with ML2/OVN and we need to use the
CI infrastructure upstream DNS server directly instead.
Cloud-internal instance name DNS resolution still works because
DNS responses will be intercepted by Open vSwitch and the
ovn-controller when it knows it can provide an answer to the
query being sent to the real server.

Fix address used for name server

---

roles/setup-networking-env/tasks/main.yaml

While investigating an issue where test jobs bomb out early due to
DNS resolution apparently not working, do a pre-flight check where
we attempt to resolve both names for which our DNS server has
authority and names that need remote lookup.

Add pre-flight check of DNS connectivity

---

playbooks/juju/pre.yaml
tox.ini

To help debug an intermittent and not reproducible issue with DNS
resolution seen in gate, have juju add cloud-init userdata that
enables debug logging for systemd-resolved.
Note that the juju model-config key `cloudinit-userdata` must be
fed in through a file and cannot be set on command line nor fed
in through the Zaza model settings environment variables.

Temporarilly set juju model-default userdata

---

playbooks/juju/pre.yaml
playbooks/new-tenant-juju/pre.yaml

This patch is to switch juju to use 2.9/stable.  This is necessary as
part of the switch to charmhub.

Switch testing to use Juju 2.9/stable

---

roles/charm-build/tasks/main.yaml

Currently charmcraft seems to pick an outdated lxc
client. charmcraft issues the following command
lxc --project charmcraft list local: --format=yaml
which is correct for me locally with lxd 4.22 but
fails on zOSCI at the moment.

Print more information about installed software

---

roles/charm-build/tasks/main.yaml

so that charmcraft picks up the lxc client from the
lxd snap instead.

Purge lxd apt package

---

roles/charm-build/tasks/main.yaml

Without this charmcraft fails with
LXD has not been properly initialized.
Consider executing 'lxd init --auto' to initialize LXD.

Initialize lxd

---

zuul.d/jobs.yaml

This patch refactors the jobs in jobs.yaml that use func-target as a
parent so that they:
* don't depend on each other.
* Use osci-lint AND a python tox as a blocker
This means that they can be used individually in charmhub branches as
there are no dependencies between the func-target jobs.

Refactor jobs.yaml to allow single func-target jobs

---

zuul.d/project-templates.yaml

These are specific unit jobs (e.g. pep8 + py*) that are targetted at a
single python version.  This is so that a charm only needs to test on
the python version for the Ubuntu version that it is going to run on.

Add templates for charm-unit-jobs-py*

---

README.md
zuul.d/project-templates.yaml

Ubuntu 21.04, Hirsute Hippo, went EOL on Jan 20, 2022. This removes the
hirsute targets from the project-templates.yaml.

Remove hirsute from project templates

---

zuul.d/jobs.yaml

This (in the new-world of charmhub migration) will stop template jobs
from running func-target until the charm-build is done.

Stop func-target-pre-jobs from running until charm-build is run

---

zuul.d/jobs.yaml

This is to ensure that charm-build really does run before the
func-target jobs.  For classic charms this should be a no-op and not
affect those jobs.

Make charm-build a hard dependency of func-target-pre-jobs

---

zuul.d/jobs.yaml

Manila Netapp needs to know the root volume aggregate. Add it to the set
of values provided in the job.
Related-Bug: 1922214

Update netapp vars for manila netapp functional job

---

zuul.d/jobs.yaml

Octavia takes a long time build and recently timed out in gate
*1 . Taking longer than 30mins to build a charm seems
excessive but thats where we are.
*1 https://openstack-ci-reports.ubuntu.com/artifacts/6ea/826711/8/check/charm-build/6ea5484/job-output.txt

Increase charm build timeout

---

roles/charm-build/tasks/main.yaml

... between LXD and Charmcraft over device naming.

Pin LXD to 4.22/stable due to recent breakage

---

zuul.d/jobs.yaml

Due to a misunderstanding on my part, the 'simple' jobs (such as
focal-wallaby) only had the tox-pyVV as a job dependencies as I though
the parent job's dependencies were merged.  However, this is not the
case. Declaring a 'dependencies' key in a job replaces the parent job's
'dependencies' key; in this case it means that the func job won't wait
for charm-build of the lint.  This patch corrects that.

Ensure that simple function jobs have required dependencies

---

zuul.d/project-templates.yaml

This is to allow the .zuul.conf to reference the long lived
python3 jobs.

Add more placeholder templates for the charmhub migration

---

playbooks/base/pre.yaml
roles/prepare-package-environment/tasks/main.yaml

The previous test of prepare-package-environment was done as root.
However running as non-root user causes the apt lock check to fail.
This change re-enables prepare-package-environment and switches
the lock check to run as root.

Use sudo in apt lock check

---

roles/charm-build/tasks/main.yaml

Looks like the 4.22 channel has gone so bump to 4.23.
```
channels:
latest/stable:    4.24-c92c0b2  2022-03-25 (22754) 82MB -
latest/candidate: 4.24-c92c0b2  2022-03-24 (22754) 82MB -
latest/beta:      4.23          2022-03-12 (22652) 82MB -
latest/edge:      git-03a4e69   2022-03-25 (22768) 82MB -
4.24/stable:      4.24          2022-03-22 (22710) 82MB -
4.24/candidate:   4.24          2022-03-22 (22710) 82MB -
4.24/beta:        ↑                                     
4.24/edge:        ↑                                     
4.23/stable:      4.23          2022-03-13 (22652) 82MB -
4.23/candidate:   4.23          2022-03-10 (22633) 82MB -
4.23/beta:        ↑                                     
4.23/edge:        ↑                                     
4.0/stable:       4.0.9 …
```

Bump LXD channel

---

zuul.d/jobs.yaml

Switch the job to depend on from py39 to py310 to align with
jammy's (recent) default of Python3.10

Jammy's python is 3.10 so switch jammy-yoga dependency

---

zuul.d/jobs.yaml

Without quoting 3.10, YAML evaluates it as `3.1` which isn't desired

Quote 3.10 for unit jobs

---

roles/handle-func-test-pr/files/process_func_test_pr.py
unit_tests/test_process_func_test_pr.py

Substitution of git url links in test-requirements with
func-test-pr does not consider branch name in git url.
This patch adds stable branch regex to consider for
substitution.

Fix func-test-pr handling to support stable branches

---

roles/charm-build/tasks/main.yaml

This change add retries to lxd snap installation to make this task more
robust and to overcome hiccups found in the Snap store detected by the
CI jobs.
https://docs.ansible.com/ansible/latest/user_guide/playbooks_loops.html#retrying-a-task-until-a-condition-is-met

Retry LXD snap installation.

---

roles/charm-build/tasks/main.yaml

The `until` check seems to be wrong resulting in jobs failing with:
"msg": "The conditional check 'result.rc == 0' failed. The error was: error while evaluating conditional (result.rc == 0): 'dict object' has no attribute 'rc'"
This reverts commit e25b200bf82884d973eae476c18718da30d2b395.

Revert "Retry LXD snap installation."

---

roles/charm-build/tasks/main.yaml

charmcraft 1.6 renamed the environment variable from CHARMCRAFT_STAGE to
CRAFT_STAGE breaking charms building.
https://github.com/canonical/craft-parts/commit/6c18447497897794dc9ea86f164fb21c035f12d1

Pin charmcraft to 1.5/stable

---

zuul.d/jobs.yaml

Zuul will retry the pre-test steps up to $attempts times, this change
increases how tolerant we are to infrastructural issues that can cause
a job to fail early

Increase setup attempts from 2 to 4

---

zuul.d/jobs.yaml

Bumping the default up to 4 seems to have reduced the failures seen
during job preparation. Make the same change to the func-target job.

Update func-target attempts as well

---

roles/prepare-package-environment/tasks/main.yaml

Extend the apt lock timeout.
Fixes: #195

Fix intermittent failures due to dpkg-lock

---

playbooks/juju/post.yaml

This is a CI environment with no state secrets, the files could
contain valuable information for triaging a problem.
Incidentally this also works around a bug in juju crashdump which
currently renders the crashdumps empty.

Also get files with strict permissions in crashdump

---

zuul.d/project-templates.yaml

This is needed for the stable/victoria branch as it needs to test
the focal-ussuri job, but doesn't need to test the bionic-ussuri job,
nor be dependent on tox-py36.

Add a focal-ussuri specific functional job template

---

zuul.d/jobs.yaml
zuul.d/project-templates.yaml

Add the kinetic-zed and jammy-zed targets for running tests
on 22.10 and 22.04 with the Ubuntu Cloud Archive.

Add kinetic-zed and jammy-zed

---

roles/prepare-package-environment/tasks/main.yaml

CI is still sometimes hitting failures when an apt lock
is still present *1 . This adds additional apt lock checks prior to
apt calls.
http://10.245.164.110/t/openstack/stream/e63240075f0f430baac9a5fae10ee77b?logfile=console.log

More apt lock checking

---

playbooks/juju/pre.yaml

Include a cloud-init configuration chunk to setup machines to always
include phased updates when installing packages via apt, this ensures
that the CI is an early user of packages that were pushed into the
-updates pocket and are still being rolled up.
A report of what packages are being phased at any given time with its
current percentage progress can be found
https://people.canonical.com/~ubuntu-archive/phased-updates.html
For more details see
https://discourse.ubuntu.com/t/phased-updates-in-apt-in-21-04/20345

Always include phased updates.

---

zuul.d/jobs.yaml

The default zaza model deploy timeout is 3600 if the TEST_DEPLOY_TIMEOUT
environment variable is not set.  However, there are some slower nodes
on ServerStack so this patch provides a bit more breathing space for a
model deployment.

Extend the timeout to 2 hours (default 3600)

---

main.yaml

This is temporary, to give space to get the charmhub migration patches
through the system.

Disable the charmed-openstack-tester periodic repositories

---

roles/charm-build/defaults/main.yaml
roles/charm-build/tasks/main.yaml

Allow the osci.yaml to include a var `charmcraft_channel` that can be
optionally used to override the default charmcraft channel that the snap
installs from.  This is to allow different branches to control which
version of charmcraft that they should use.  The default version is
fixed at "1.5/stable" which is used for all the backport branches.

Allow osci.yaml to control the charmcraft build version

---

zuul.d/project-templates.yaml

This allows execution of voting jammy-yoga tests without having to
run focal-yoga tests. Additionally, this allows for dropping of the
charm-yoga-functional-jobs template.

Add jammy-yoga to charm-zed-functional-jobs

---

zuul.d/jobs.yaml

Octavia functional tests are sometimes exceeding the timeout *1
even though the tests are working as designed. A recent run
looked like this:
Time	Task
35	Setting up deployment environment
50	Deployment
50	Configure
10	LBAASv2Tes
01	CharmOperationTest
45      policyd tests
This PR increases the timeout to 4 hours. This has the
downside that an executor will be tie'd up for an extra hour
if the test is stuck.
*1 https://openstack-ci-reports.ubuntu.com/artifacts/300/842207/5/check/focal-victoria-ha/300928c/job-output.txt

Increase timeout for func-target

---

playbooks/juju/post.yaml

The flag `-j '*'` is translated to `journalctl -u '*'` which makes
journalctl to match the logs for all the units of the system in a single
stream. juju-crashdump will produce a single file named '*.log' as
shown here:
[...]/2/baremetal/journalctl/
[...]/2/baremetal/journalctl/*.log

Capture journalctl.

---

zuul.d/jobs.yaml

This change sets the environment variable TEST_ZAZA_BUG_LP1987332 to
enable the workaround for bug LP:# 1987332. This change can be dropped
once that gets fixed.
Related-Bug: #1987332
Related-PR: openstack-charmers/zaza#556

Enable workaround for bug 1987332

---

playbooks/juju/pre.yaml
playbooks/new-tenant-juju/pre.yaml
zuul.d/jobs.yaml

For a func-test style job, allow the juju version to be overridden
in the project's variables, or job variables.
e.g. from an osci.yaml
- project:
templates:
- charm-unit-jobs-py36
- charm-unit-jobs-py38
check:
jobs:
- focal-yoga
vars:
needs_charm_build: true
charm_build_name: hacluster
build_type: charmcraft
juju_snap_channel: "2.8/stable"
This would override the default (currently 2.9/stable) with
2.8/stable

Enable osci.yaml/jobs to override juju channel

---

main.yaml
playbooks/charm/publish.yaml
roles/publish-charm/defaults/main.yaml
roles/publish-charm/tasks/main.yaml
site-vars.yaml
zuul.d/jobs.yaml
zuul.d/pipelines.yaml
zuul.d/project-templates.yaml
zuul.d/secrets.yaml

* Update project-templates, jobs, playbook, roles
to support publishing charms to charmhub
* Add promote pipeline to listen on gerrit change-merged event
* Introduce new variable publish_charm to decide
whether to publish charm or not
With this patch, the charms should set following variables
in osci.yaml
- needs_charm_build
- build_type
- charm_build_name
- charmcraft_channel
- publish_charm

Add support to publish charms to charmhub

---

zuul.d/jobs.yaml

publish-charm job includes charm-build role which took
around 20 minutes for keystone-k8s charm. The timeout
value need to be checked against all the sunbeam charms.
Setting publish-charm job timeout to 60 minutes to allow
publish-charm job to succeed for all the sunbeam charms.

Change publish-charm job timeout to 60 minutes

---

zuul.d/pipelines.yaml

The promote pipeline introduced in commit 2b7b0f21 uses the sqlreporter
keyword for success and failure events rather than the mysql key. The
sqlreporter key appears to be a newer Zuul construct.

Change sqlreporter to mysql

---

roles/publish-charm/tasks/main.yaml

zuul.project.src_dir provides relative path from
home directory. In case of file lookups using
ansible builtin module lookup, add absolute paths
for lookups.
Add zuul.executor.work_root to get absolute path
for charm metadata.yaml in publish_charm task.

use aboslute path for file lookups

---

roles/publish-charm/tasks/main.yaml

Change the utility from command to shell for the
charm upload task.
Include verbosity for charmcraft command.

Add verbose to charmcraft commands

---

roles/charm-build/tasks/main.yaml
roles/upload-charm/tasks/main.yaml

Charmcraft allows building multiple charm artifacts from a single repository, pivoting on Ubuntu series and target architectures.
To support this, instead of uploading a single named .charm artifact, we archive up all .charm files in the work directory and upload that archive to Swift.
The change re-uses the archive type and file naming from the old reactive build job, and as such some of the handling becomes equal for both charm types.

Upload multiple charmcraft charms

---

zuul.d/jobs.yaml

Jobs can be triggered using experimental pipeline
by updating osci.yaml in corresponding projects.
This patch set post-review to true for publish-charm job so that it can be triggered only after review
even in experimental pipeline.

Set post-review to true for publish-charm job

---

zuul.d/jobs.yaml

Increase charm-build timeout from 3600 to 7200
charm-octavia [1] and charm-octavia-diskimage-retrofit [2] were
hitting timeouts with timeout set to 3600.
[1] https://review.opendev.org/c/openstack/charm-octavia/+/850215
[2] https://review.opendev.org/c/openstack/charm-octavia-diskimage-retrofit/+/847500

Increase charm-build timeout from 3600 to 7200

---

roles/charm-build/tasks/main.yaml
zuul.d/jobs.yaml

Previously the `charm-build` job had to run on a Xenial image in order for `charm-tools` to produce compatible reactive charms.
Since then all charms have been updated to make use of `charmcraft` to execute the build.
Charmcraft executes the build in LXD containers using the series specified in the charmcraft.yaml file, and as such there is no longer a need to keep the outer image on Xenial.

Update charm-build job to run on jammy

---

roles/charm-build/tasks/main.yaml
zuul.d/jobs.yaml

Ansible playbook not compatible with jammy atm. Also our zuul version does not support 3.10
This reverts commit 36de28090dc6498b3bba76ac703f07f729d3af20.

Revert "Update charm-build job to run on jammy"

---

zuul.d/project-templates.yaml

This needs to be 'on' as we need to verify that jammy-zed is working.

Enable voting for jammy-zed job

---

playbooks/juju/post.yaml

Run "juju show-unit" to get a better understanding of the data in the relations which helps to troubleshoot why a given relation didn't run, or if it run but to check if the hook had all the data available.

Capture juju show-unit

---

playbooks/sqalab/pre.yaml
playbooks/sqalab/run.yaml
playbooks/sqalab/templates/credentials.yaml.j2
zuul.d/jobs.yaml
zuul.d/secrets.yaml

Add playbooks, job, and secrets for integration between zuul and the SQA lab.
- The integration relies on [https://github.com/canonical/weebl-tools](weebl-tools) (weebl in the sqa test server/dashboard). 
- This PR can only be merged once the firewall rules between serverstack and the sqa lab are sorted out 
- [Related PR in charmed-openstack-tester](https://github.com/openstack-charmers/charmed-openstack-tester/pull/88)

Add integration in sqa lab

---

tox.ini

Tox now chokes on spaces in the `passenv` key and requires it to be a comma separated or multi-line list.

tox.ini: Fix passenv list

---

zuul.d/jobs.yaml

Tox 4 was introduced during Antelope development and requires changes, therefore we are pinning zosci jobs to tox<4 for branches <= stabe/zed. The master branches will move forward with the latest tox.
This change is inline with gmann's upstream change: https://review.opendev.org/c/openstack/openstack-zuul-jobs/+/867849

Pin tox<4 for stable branches <= stable/zed

---

zuul.d/jobs.yaml

Add the following charm stable branches to the regular expressions:
* trilio charms: stable/4.0, stable/4.1, stable/4.2
* rabbitmq-server, pacemaker-remote, hacluster charms: stable/focal
* rabbitmq-server, pacemaker-remote, hacluster, mysql-innodb, mysql-router, openstack-loadbalancer charms: stable/jammy
* vault charm: stable/1.5, stable/1.6, stable/1.7, stable/1.8
* ovn charms: stable/20.03, stable/20.12, stable/21.09, stable/22.03, stable/22.09

Update base job stable branches for various charms

---

roles/handle-func-test-pr/files/process_func_test_pr.py
unit_tests/test_process_func_test_pr.py

The forked repo name may be different from the
original repository name. Get the forked repo
name from API response and use the same for
applying updates to requirements file.

[func-test-pr] Update repo name from api response

---

zuul.d/jobs.yaml
zuul.d/project-templates.yaml

Add the lunar-antelope and jammy-antelope targets for running tests on 23.04 and 22.04 with the Ubuntu Cloud Archive.

Add lunar-antelope and jammy-antelope

---

zuul.d/semaphores.yaml

The cloud where zosci runs has reduced its cpu overcommit to reduce the amount of pressure that the CI jobs are putting on the control plane which has been leading to outages, this is a change that goes into that direction, less jobs, but more reliable runs.

Reduce func-test concurrency from 12 to 10

---

zuul.d/jobs.yaml

The TEST_REGISTRY_PREFIX environment variable is consumed by zaza-openstack-test when magnum is deployed, this registry contains the images needed for successfull k8s deployment, for more details see zaza.openstack.charm_tests.tempest.utils for more details.

Add TEST_REGISTRY_PREFIX environment variable

---

zuul.d/jobs.yaml
zuul.d/project-templates.yaml

Instead of creating an charm-antelope-unit-jobs and charm-antelope-functional-jobs template, we switch to using the charm-unit-jobs and charm-functional-jobs templates with their 'branches' specyfing the jobs to run. This allows for managing jobs in a central location.
This is similar to changes being made to openstack-zuul-jobs, such as in [1], and you'll notice I've borrowed the inline comments from gmann.
[1]
https://review.opendev.org/c/openstack/openstack-zuul-jobs/+/873907

Update charm-unit-jobs and charm-functional-jobs for antelope

---

zuul.d/project-templates.yaml

branches must be a list of regexp.
The key "branches" appears more than once; duplicate keys are not
permitted.
The error appears in the following stanza:
branches: ^stable\/(1\.5|1\.6|1\.7|1\.8)$
branches: ^stable\/(4\.0|4\.1|4\.2)$
branches: ^stable\/(20\.03|20\.12|21\.09|21\.10|22\.03|22\.09)$
branches: ^stable\/(focal|jammy)$
branches: ^stable\/(train|ussuri|victoria|wallaby|xena|yoga|zed)$
branches: ^stable\/(luminous|mimic|nautilus|octopus|pacific|quincy|quincy\.2)$

Fix project-templates branches key.

---

zuul.d/jobs.yaml

All charm builds now happen via charmcraft which launches a LXD container with the base specified in charmcraft.yaml making the Ubuntu series where the job runs less relevant, and having a newer version is better from the perspective of the kernel, snapd and lxd.

Run charm-build job on focal-medium

---

zuul.d/jobs.yaml

It seems that the list of branch regex's is not
working so let's see if functional jobs get
scheduled for master after this change.

Revert base jobs branch regex's to a single regex

---

zuul.d/project-templates.yaml

The antelope charm batch results in many circular
dependencies due to bundles that are using charms
that do not yet have antelope support enabled.
Voting needs to be re-enabled once the antelope
batch is merged.

Set jammy-antelope job to non-voting

---

zuul.d/jobs.yaml

Some charms, such as the magpie charm,  have gates that are not tied to UCA pockets.

jobs: Add plain lunar job

---

zuul.d/project-templates.yaml

This update adds non-openstack stable branch names to jammy-zed, jammy-antelope, and lunar-antelope jobs. If any of the charms with corresponding stable branch names want to run the generic charm-functional-jobs in their .zuul.yaml, they need zosci to understand their stable branch names.

Update charm-functional-jobs stable branches

---

main.yaml

This PR registers two new charms:
* charm-watcher, principal charm to configure OpenStack Watcher
* charm-watcher-dashboard, subordinate charm that extends openstack-charm to configure the watcher-ui plugin.

Add Watcher

---

roles/publish-charm/defaults/main.yaml
roles/publish-charm/tasks/main.yaml

Support publishing machine charms (no oci image). There is duplicate code introduced here. Rather then get into ansible hell the publishing code should be wrapped into an ansible module in the future.

Support publishing machine charms

---

main.yaml

Add openstack/charm-heat-k8s to gerrit untrusted projects.

Add charm-heat-k8s to untrusted projects

---

zuul.d/jobs.yaml

charm-octavia[1] and charm-octavia-diskimage-retrofit[2] were hitting timeouts with timeout set to 7200.
[1] https://review.opendev.org/c/openstack/charm-octavia/+/858608
[2] https://review.opendev.org/c/openstack/charm-octavia-diskimage-retrofit/+/896680

Increase charm-build timeout from 2h to 3h

---

zuul.d/project-templates.yaml

The noop-jobs project template allows projects to define a check and/or gate job that always succeeds, this is mainly (if not only) used by git branches that have been cleaned up, for example:
https://opendev.org/openstack/charm-mysql-innodb-cluster/commit/0d8e7accae509c4ae332c169463685e16699d600
The `noop` job is a virtual job defined by Zuul itself, see https://opendev.org/zuul/zuul/src/commit/d1ffc204e4b4955f2a47e7e37618fcf13bb1b9fd/zuul/model.py#L8018-L8029
This job template definition was borrowed from https://opendev.org/openstack/openstack-zuul-jobs/src/branch/master/zuul.d/project-templates.yaml#L18

Add noop-jobs project template

---

zuul.d/jobs.yaml
zuul.d/project-templates.yaml

Also includes various updates relating to py311.

Add tox-py311 job and project templates

---

zuul.d/project-templates.yaml

The stable/2023.2 needs to test the correct functioning of 2023.1/antelope to service users coming from an openstack upgrade.

Run jammy-antelope on stable/2023.2 branch

---

zuul.d/project-templates.yaml

For the charm-functional-jobs remove the lunar-antelope job as it's no
longer needed.

Remove lunar-antelope from the master branch

---

zuul.d/secrets.yaml

This reverts commit bc869a4a79fa624012cfe0e8ce7b049f9c56d049.

Revert "Switch storage for CI artifacts to PS5"

---

zuul.d/jobs.yaml

There are some jobs that are timing out after 4 hours because of this timeout. Increasing to 5 hours for now to help these jobs complete.

Increase the timeout for func-target job

---

roles/upload-swift/tasks/main.yaml

This commit reverses a change that added index.html at the end of the log_url for Zuul logs. As far as I can tell this is causing the URL to be wrong and cause 404 errors. I think removing the `index.html` should fix this. I'm not sure why this is happening in the first place, unfortunately.

Revert pull request 305 add-index-html

---

playbooks/juju/pre.yaml

Juju's '2.9' snap track publishes a snap with the classic confinement, while juju>=3.1 uses a strict confinement, instead of asking users to understand this, we encapsulate this information into the ansible task.

Install the juju snap as classic only when the channel is 2.9

---

zuul.d/pipelines.yaml

This commit closes issue 310. It adds pipelines for each day of the week for running a job weekly. This commit allows us to break up weekly jobs over multiple days to distribute the load.
I think I have this set up right. I copied off the existing weekly job's format.
I did set the time to 0111 UTC each of the days because that day should be outside of the working days of the folks in our organization. I recognize that time does overlap with the working hours of East Asian, though. If there is a better time at which to trigger these jobs, I'm open to suggestions.

Add weekly pipelines for every day of the week

---

zuul.d/jobs.yaml
zuul.d/project-templates.yaml

Two new job templates are added (noble-caracal and jammy-caracal) that run when changes are detected in the following branches:
- main
- master
- stable/2024.1  # OpenStack
- stable/24.03   # OVN
- stable/noble   # Ubuntu
Depends-On: https://github.com/openstack-charmers/zaza/pull/608

Add OpenStack 2024.1 (Caracal) jobs

---

playbooks/juju/pre.yaml

The commit 16b1561 introduced a dynamic evaluation to set the `classic` property to true/false when installing the juju snap, although that line produces a "False" which Ansible is evaluating to true.
This change takes a different approach dropping the use of an inline-if which was producing a string value, now it's being used a conditional expression to force the evaluation as a boolean.

Rewrite jinja2 snippet to determine if juju snap should be classic

---

playbooks/juju/pre.yaml

The juju snap when installed in strict confirment (>=3.0) can't create the directory ~/.local/share/ due to the restriction in the AppArmor profile, machines used by Zuul don't have that directory available by default.
This change adds a new task before installing juju to create the needed directories. The ansible module ansible.builtin.file creates intermediary directories (if missing).

Create ~/.local/share/juju directory before running juju

---

playbooks/juju/pre.yaml

The juju snap in strict mode can't access /tmp. This change moves the charm-test-infra and other temporary files under /home/ubuntu to allow the juju client read them.

Do not use /tmp for intermediate files.

---

roles/juju-setup/tasks/main.yaml

Juju stopped creating a default model when a controller is bootstrapped, this new task checks for the existence of the model, if it's not present, it creates it.

Add default juju model if needed.

---

roles/juju-setup/tasks/main.yaml

Juju>=3.0 added the `--file` flag when passing the default values for a model in a yaml file.
This change checks the juju client's version using `dpkg --compare-versions`.

Pass --file when running juju model-defaults

---

playbooks/juju/run.yaml
roles/handle-constraints-url/defaults/main.yaml
roles/handle-constraints-url/tasks/main.yaml

The tox job[0] accepts the tox_constraints_file variable, although its implementation checks that the string references a locally available file[1]. This prevents from passing a url to pip.
This change reads the content from a url passed via pip_constraints_url and renders it in a temporary file that gets referenced to be used by tox.
[0] https://zuul-ci.org/docs/zuul-jobs/latest/python-jobs.html#jobvar-tox.tox_constraints_file
[1] https://opendev.org/zuul/zuul-jobs/src/branch/master/roles/tox/tasks/main.yaml

Handle constraints from a URL

---

roles/handle-constraints-url/tasks/main.yaml

This change makes the handle-constraints-url validate more aggressively the pip_constraints_url holds a value that can be used, also a new task is introduced to only use the constraints file when its size is larger than zero.
```
TASK [handle-constraints-url : GET the constraints file]
focal-medium | ERROR
focal-medium | {
focal-medium |   "dest": "/home/ubuntu/constraints.a7h1xj9v.txt",
focal-medium |   "elapsed": 0,
focal-medium |   "gid": 1000,
focal-medium |   "group": "ubuntu",
focal-medium |   "mode": "0600",
focal-medium |   "msg": "An unknown error occurred: a bytes-like object is required, not 'str'",
focal-medium |   "owner": "ubuntu",
focal-medium |   "size": 0,
focal-medium |   "state": "file",
focal-medium |   "uid": 1000,
focal-medium |   "url": null
focal-medium | }
```

Get the constraints file only when holds a valid value

---

roles/handle-constraints-url/tasks/main.yaml

The value passed in the `when` stanza uses None instead of null.
Fixes the error: `'null' is undefined`

Use `is not None` instead of `!= null`.

---

roles/handle-constraints-url/tasks/main.yaml

Jinja2 tests against `none` (lowercase). When using `None` (capitalized), the following error is raise:
The conditional check '...' failed. The error was: template error while templating string: no test named 'None'.
See https://github.com/pallets/jinja/issues/520 for more details.
Issue seen in the gate at
https://openstack-ci-reports.ubuntu.com/artifacts/b6d/908775/3/check/jammy-zed/b6df748/job-output.txt

Use `none` instead of `None`.

---

roles/handle-constraints-url/tasks/main.yaml

The ansible.builtin.stat module returns a dictionary where the key to use is 'stat' in order to get the file stats. Add the missing stat key. Failure to do this causes the task to fail with size not being a key in the dictionary.
ref: https://docs.ansible.com/ansible/latest/collections/ansible/builtin/stat_module.html#ansible-collections-ansible-builtin-stat-module

Check the stat dictionary's size, not the variable's size

---

roles/handle-constraints-url/tasks/main.yaml

This change updates the handle-constraints-url role to set the TEST_CONSTRAINTS_URL instead of TOX_CONSTRAINTS_FILE to avoid collision with upstream's zuul.
Related-Pr: https://github.com/openstack-charmers/release-tools/pull/295

Set TEST_CONSTRAINTS_FILE instead of TOX_CONSTRAINTS_FILE

---

zuul.d/jobs.yaml

This allows the jobs to install the right libjuju version based on the snap channel that juju is being installed from.
Depends-On: https://github.com/openstack-charmers/zaza-openstack-tests/pull/1185
Depends-On: https://github.com/openstack-charmers/zaza/pull/608

Set a tox_constraints_file for caracal jobs.

---

zuul.d/jobs.yaml

The *-bobcat jobs are run by master branch AND stable/2023.2, while the former would be OK to be moved to use juju-3.x, the latter is not.
Without this change, bobcat jobs running in master will install juju-2.9, but zaza from master making it install libjuju-3.x. This change introduces the constraint which will be honored by master and discarded by stable/2023.2 although that stable branch installs zaza from stable/bobcat which has libjuju pinned to `<3.0`.

Set constraints for bobcat jobs

---

zuul.d/project-templates.yaml

and remove lunar job,Lunar is EOL so stop testing it for antelope.  Mantic is only for 2023.2
and therefore is removed for 2024.1 testing (curently main/master).
Mantic will be removed when it goes EOL.

Remove mantic from dev

---

roles/handle-constraints-url/tasks/main.yaml

Ansible's get_url module uses the last modified time of an existing file on disk to only download files that have potentially changed. The handle-constraints-url role will create a temporary temporary file to store the constraints file, which leaves the last modified time as extremely recent. This causes the remote webserver to respond with an HTTP 304 (content not modified) and the constraints do not get properly set.
This change addresses this by adding force: true to the get_url module which will always download the specified file and not use the file's last modified timestamp.

Force download of constraints files

---

zuul.d/jobs.yaml

Make the gate to use juju 2.9 since zaza has been exhibiting different failures when trying to be used with juju 3.x, this will be kept until zaza gets more robust.
Depends-On: https://github.com/openstack-charmers/zaza/pull/652

Comment out juju_snap_channel and pip_constraints_url

---

zuul.d/project-templates.yaml

i.e. we want jammy-bobcat bundle to run for charm-functional-jobs on the
stable/2024.1 branch of repositories.

Add stable/2024.1 branch to jammy-bobcat for c-f-jobs

---

zuul.d/project-templates.yaml

It occurred to me that jammy-caracal charms need to support running
jammy-antelope to be able to do the SLURP release from antelope to
caracal.
Thus we add stable/2024.1 branch into the jammy-antelope job.

Add stable/2024.1 to jammy-antelope

---

zuul.d/jobs.yaml
zuul.d/project-templates.yaml

Use charmcraft 3.x/beta for noble support on master/main branches. Only run the noble-caracal tests on the master/main branches.

Update noble-caracal test jobs

---

roles/handle-func-test-pr/files/process_func_test_pr.py
roles/handle-func-test-pr/tasks/main.yaml
unit_tests/test_process_func_test_pr.py

The stable/X branches of OpenStack use python version specific
requirements files, in the form `requirements-pyX.txt`. The way that
func-test-pr was implemented limited scanning/updating files to those in
the form `requirements.txt`, etc.
This patch introduces globbing support, and then in the ansible
playbook, globbing for `requirements*.txt` rather to enable multiple
files to be updated via the func-test-pr.

Modify func-test-pr to work with globbed filenames

---

zuul.d/jobs.yaml

Running into issues when building charms with charmcraft3 on focal. The symptom is failing systemd services such as
```
systemd-resolved.service: Failed to set up mount namespacing: /tmp:
Permission denied
```
Jammy does not have this issue.

Charmcraft3: use jammy for building

---

zuul.d/jobs.yaml

Update environment to use juju3 for noble-caracal jobs by default.

Use juju3 for noble-caracal jobs by default
